# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 1.1.{build}


#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: AIbS1wYpJuS5smWmeVDw5Bs9BmYV5q66BiJvg6hiJHHoELHnreIdclPuhBcaDdsS

# Allow WMF5 (i.e. PowerShellGallery functionality)
image:
  - Visual Studio 2017


# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: |
      Get-PackageProvider -Name NuGet -Force;
      Install-Module -Name Psake -Force;
      Invoke-psake -buildFile .\default.ps1 -taskList default
      exit ( [int]( -not $psake.build_success ) )
